- name: Error handling
  hosts: localhost
  tasks:
    #checking user exist or not, if not available it should proceed further
    - shell: id roboshop
      register: out
      ignore_errors: yes

    - debug:
        msg: User details - {{ out.stdout }}