- name: Loops Demo
  hosts: localhost
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Fruit - {{ item}}"
      loop: #list
        - apple
        - banana
        - orange

    - name: Print with quantity
      ansible.builtin.debug:
        msg: "Fruit - {{ item['name'] }}, Quantity - {{ item.quantity }}"
                      #1st method accessing map     #2nd method accessing map
      loop:
        - { name: apple, quantity: 100} #map
        - { name: banana, quantity: 200}
        - { name: orange, quantity: 300}