- name: retrive Hashicorp secrets
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/test:MYPASS token={{ vault_token }} url=https://vault.meppk.xyz:8200 validate_certs=False')}}"